### ISSUE TITLE
Issues with some monsters

### ISSUE THREAD

**Issue by Gothic-HP** [Realm667/HPack#1]
-Blood Lich lacks attack sounds.
-Reiver Ghost lacks sounds, projectile sprites, and has badly palleted ressurection frames.
-Ophidian Lord lacks attack sounds.

Everything is fixed on this file:
[Monster_Update.zip](https://github.com/Realm667/HPack/files/2681939/Monster_Update.zip)

**Comment by Tormentor667** [comment]
Would you mind doing a proper commit? :)

**Comment by Gothic-HP** [comment]
Thanks, I was waiting for approval
