### ISSUE TITLE
Repo Access Request - Serge Jaeken

### ISSUE THREAD

**Issue by XaserAcheron** [Realm667/HPack#26]
Bit of an odd place to leave this, since this isn't necessarily a public issue, but: @Tormentor667 would you be up for giving @SergeJkn (Serge Jaeken) commit access? he DM'd me recently and is interested in chipping in on maps -- he's got one in the project and has another WIP he's interested in finishing, but I don't have admin access so can't do it myself.

Thanks! Just dropping this by here so I don't forget again. :P

**Comment by Tormentor667** [comment]
Just did it :)
