### ISSUE TITLE
Finish Satyr Archer sprites

### ISSUE THREAD

**Issue by XaserAcheron** [Realm667/HPack#7]
The Satyr Archer is currently missing rotation sprites for their attack -- this probably ought to be resolved before we mark this project 'done'. ;)

**Comment by Blue-Shadow** [comment]
I wonder if Vader could help. It might be worth asking him.

**Comment by Tormentor667** [comment]
Let's try it @VaderTheEye :)

**Comment by Gothic-HP** [comment]
Done [https://github.com/Realm667/HPack/commit/375c79935859b70eb66e24684795b9097931ae1c](https://github.com/Realm667/HPack/commit/375c79935859b70eb66e24684795b9097931ae1c)

**Comment by Gothic-HP** [comment]
Done [https://github.com/Realm667/HPack/commit/375c79935859b70eb66e24684795b9097931ae1c](https://github.com/Realm667/HPack/commit/375c79935859b70eb66e24684795b9097931ae1c)
